import Testing

@testable import AdventOfCode

struct Day07Tests {
  let example = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

  @Test func testPart1() async throws {
    let challenge = Day07(data: example)
    #expect(try await challenge.part1() == 21)
  }
}
